### ISSUE TITLE
Support for CORIOmaster 1 (C3-540)

### ISSUE THREAD

**Issue by dombuerkler** [bitfocus/companion-module-tvone-corio#1]
Would it be possible to add support for CORIOmaster Version 1 (C3-540)?
I tried this module, but i was unable to control my C3-540.

Kind regards
Dom

**Comment by theMikeChow** [comment]
Adding to request for C3-540 support. 

Simple preset and source change commands would be extremely helpful.

[Link to API](https://api.tvone.com/products/c3-series/c3-5xx/index.html)

Thanks!

**Comment by daniep01** [comment]
Corio Master API is different to that used for the C2 range, and would be best placed in a new separate module.
